site_name: Notes

theme:
  name: 'material'
  features:
    - navigation.tabs
    - search.suggest
    - search.share

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: octicons/repo-24

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra_css:
    - stylesheets/style.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - EL5131:
      - Science and Technology: EL5131/'Science and Technology.md'
  - PC5131:
      - Checklist: pc5131/index.md
      - Rotational Mechanics: pc5131/rotation.md
      - Waves I: pc5131/waves-one.md
  - PC5132:
      - Checklist: PC5132/index.md
      - Chapter 4 Practice Qns: PC5132/chapter4.pdf
      - Chapter 5 Practice Qns: PC5132/chapter5.pdf
  - CM5132:
      - Home: CM5132/index.md
      - CM5132/energetics.md
      - CM5132/thermodynamics.md


extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/ThePyProgrammer/notes

copyright: Copyright &copy; 2022 Prannaya Gupta
